name: Build and Deploy WoWThreads

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build addon
      run: echo "Building the addon..." # Adjust this command to your build process

    - name: Package addon
      run: |
        mkdir -p package
        # Copy only the necessary files to the package directory
        cp README.md package/
        cp Docs/WoWThreads-complete.md package/
        # Check if src directory exists and copy it if present
        if [ -d "src" ]; then cp -r src package/; fi
        # Create the zip file excluding .github, .vscode, and .gitignore
        cd package
        zip -r ../WoWThreads.zip ./*
        cd ..
    
    - name: List files for debugging
      run: ls -alh package/
    
    - name: List root directory files for debugging
      run: ls -alh

    - name: Check zip file
      run: unzip -l WoWThreads.zip

    - name: Upload to CurseForge
      env:
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      run: |
        curl -X POST \
        -H "x-api-key: $CURSEFORGE_API_KEY" \
        -F "file=@WoWThreads.zip" \
        -F "metadata={\"changelog\": \"Automated build\", \"changelogType\": \"markdown\", \"displayName\": \"WoWThreads v1.0\"}" \
        https://minecraft.curseforge.com/api/projects/<PROJECT_ID>/upload-file

    - name: Cleanup
      run: rm -rf package WoWThreads.zip
