name: Publish to CurseForge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Package files
        run: |
          mkdir -p package
          cp -r path/to/your/files/* package/
          cd package
          zip -r ../WoWThreads.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: WoWThreads
          path: WoWThreads.zip

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: WoWThreads
          path: ./WoWThreads.zip

      - name: Publish to CurseForge
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          CURSEFORGE_EMAIL: ${{ secrets.CURSEFORGE_EMAIL }}
        run: |
          curl -X POST "https://wow.curseforge.com/api/projects/1062198/upload-file" \
          -H "x-api-token: $CURSEFORGE_API_KEY" \
          -F "file=@./WoWThreads.zip" \
          -F "metadata=<metadata.json"
