name: Build and Deploy WoWThreads

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build addon
      run: echo "Building the addon..." # Adjust this command to your build process

    - name: Package addon
      run: |
        mkdir -p package
        # Copy necessary files and directories to the package directory
        rsync -av --progress Docs/WoWThreads-complete.md package/
        rsync -av --progress Libs/ package/Libs/
        rsync -av --progress Locales/ package/Locales/
        rsync -av --progress Sources/ package/Sources/
        rsync -av --progress LICENSE package/
        rsync -av --progress README.md package/
        rsync -av --progress WoWThreads*.toc package/
        # Create the zip file excluding .github, .vscode, and .gitignore
        cd package
        zip -r ../WoWThreads.zip ./*
        cd ..
    
    - name: List files for debugging
      run: ls -alh package/
    
    - name: List root directory files for debugging
      run: ls -alh

    - name: Check zip file
      run: unzip -l WoWThreads.zip

    - name: Upload to CurseForge
      env:
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        CURSEFORGE_EMAIL: ${{ secrets.CURSEFORGE_EMAIL }}
      run: |
        base64auth=$(echo -n "${{ secrets.CURSEFORGE_EMAIL }}:${{ secrets.CURSEFORGE_API_KEY }}" | base64)
        curl -v --http1.1 -X POST \
          -H "Authorization: Basic $base64auth" \
          -F "file=@WoWThreads.zip" \
          -F "metadata={\"changelog\": \"Automated build\", \"changelogType\": \"markdown\", \"displayName\": \"WoWThreads v1.0.0\"}" \
          https://www.curseforge.com/api/upload

    - name: Cleanup
      run: rm -rf package WoWThreads.zip
