name: Create Release and Upload Asset

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Retrieve version
        id: get_version
        run: |
          if [ ! -f VERSION ]; then
            echo "VERSION file not found!"
            exit 1
          fi
          VERSION=$(jq -r '.version' VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Clean up previous builds
        run: rm -rf WoWThreads.zip package

      - name: Package files
        run: |
          mkdir -p package/WoWThreads
          cp -r Docs package/WoWThreads/
          cp -r Libs package/WoWThreads/
          cp -r Locales package/WoWThreads/
          cp -r Sources package/WoWThreads/
          cp LICENSE package/WoWThreads/
          cp README.md package/WoWThreads/
          cp WoWThreads_Mainline.toc package/WoWThreads/
          cp WoWThreads_Vanilla.toc package/WoWThreads/
          cd package
          zip -r ../WoWThreads.zip WoWThreads

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Create Release
        run: |
          tag_name="v${{ env.VERSION }}"
          release_name="WoWThreads Release $tag_name"
          release_body="Release description"
          gh release create $tag_name WoWThreads.zip --title "$release_name" --notes "$release_body"
