name: Create Release and Upload Asset

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve version
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Package files
        run: |
          mkdir -p package/WoWThreads
          cp -r Docs package/WoWThreads/
          cp -r Libs package/WoWThreads/
          cp -r Locales package/WoWThreads/
          cp -r Sources package/WoWThreads/
          cp LICENSE package/WoWThreads/
          cp README.md package/WoWThreads/
          cp WoWThreads.code-workspace package/WoWThreads/
          cp WoWThreads_Cata.toc package/WoWThreads/
          cp WoWThreads_Mainline.toc package/WoWThreads/
          cp WoWThreads_Vanilla.toc package/WoWThreads/
          cd package
          zip -r ../WoWThreads.zip WoWThreads

      - name: Install GitHub CLI 
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y || {
            curl -LO https://github.com/cli/cli/releases/download/v2.20.2/gh_2.20.2_linux_amd64.deb
            sudo dpkg -i gh_2.20.2_linux_amd64.deb
            sudo apt-get install -f -y
          }

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Create Release
        run: |
          tag_name="v${{ env.VERSION }}"
          release_name="WoWThreads Release $tag_name"
          release_body="Release description"
          gh release create $tag_name WoWThreads.zip --title "$release_name" --notes "$release_body"

      - name: List release files for verification
        run: |
          gh release view "v${{ env.VERSION }}"
