name: Create Release and Upload Asset

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve version
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Package files
        run: |
          mkdir -p package/WoWThreads
          cp -r Docs package/WoWThreads/
          cp -r Libs package/WoWThreads/
          cp -r Locales package/WoWThreads/
          cp -r Sources package/WoWThreads/
          cp LICENSE package/WoWThreads/
          cp README.md package/WoWThreads/
          cp WoWThreads.code-workspace package/WoWThreads/
          cp WoWThreads_Cata.toc package/WoWThreads/
          cp WoWThreads_Mainline.toc package/WoWThreads/
          cp WoWThreads_Vanilla.toc package/WoWThreads/
          cd package
          zip -r ../WoWThreads.zip WoWThreads

      - name: Install GitHub CLI
        uses: actions/setup-gh-cli@v2

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="v${{ env.VERSION }}"
          release_name="WoWThreads Release $tag_name"
          release_body="Release description"
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create $tag_name WoWThreads.zip --title "$release_name" --notes "$release_body"

      - name: List release files for verification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release view "v${{ env.VERSION }}"
