name: Create Release and Upload Asset for WoWThreads

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version for better compatibility

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Retrieve version
        id: get_version
        run: |
          if [ ! -f VERSION.md ]; then
            echo "VERSION.md file not found!"
            exit 1
          fi
          VERSION=$(jq -r '.version' VERSION.md)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Clean up previous builds
        run: rm -rf WoWThreads.zip package

      - name: Package files
        run: |
          mkdir -p package/WoWThreads
          # Copy relevant directories and files, excluding .git, Notes, Testing, and WoWThreads.code-workspace
          cp -r AutoEquip package/WoWThreads/  # Assuming AutoEquip is a dependency or directory
          cp -r LibACE package/WoWThreads/    # If applicable, adjust for your dependencies
          cp -r Locales package/WoWThreads/   # Localization files
          cp -r Sources package/WoWThreads/   # Core source files
          cp -r Utils package/WoWThreads/     # Utility files
          cp WoWThreads.toc package/WoWThreads/  # TOC file for WoWThreads
          cp LICENSE package/WoWThreads/      # License file
          cp README.md package/WoWThreads/    # Readme
          cp VERSION.md package/WoWThreads/   # Version file
          # Exclude .git, Notes, Testing, and WoWThreads.code-workspace explicitly
          find package/WoWThreads -name ".git" -exec rm -rf {} +
          find package/WoWThreads -name "Notes" -exec rm -rf {} +
          find package/WoWThreads -name "Testing" -exec rm -rf {} +
          find package/WoWThreads -name "WoWThreads.code-workspace" -exec rm -rf {} +
          cd package
          zip -r ../WoWThreads.zip WoWThreads

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | gh auth login --with-token

      - name: Create Release
        run: |
          tag_name="v${{ env.VERSION }}"
          release_name="WoWThreads Release $tag_name"
          release_body="WoWThreads release for version ${{ env.VERSION }}"
          gh release create $tag_name WoWThreads.zip --title "$release_name" --notes "$release_body"